### ISSUE TITLE
kube-dns and RBAC on Minikube still broken??

### ISSUE THREAD

**Issue by wallrj** [jetstack/navigator#107]
Sometimes the E2E tests fail because of a failure in the check for navigator API server readiness.

(I can't find an example of the error in Travis right now)

I saw CrashLoopBackoff messages for the kube-dns Pods, so went looking again at the kube-dns configuration and our fix....adding a `kube-dns` service account.

Minikube configures the kube-dns controller with this Deployment config file:
 * https://github.com/kubernetes/minikube/blob/v0.23.0/deploy/addons/kube-dns/kube-dns-controller.yaml

Which does not specify a `serviceAccount`.

So it uses `kube-system:default`.

The `kube-dns` service account is added upstream here:
 * https://github.com/kubernetes/kubernetes/pull/38816

But that change has never been copied to Minikube.

Other projects are working around broken kube-dns RBAC with something like this:

```
# Wide open access to the cluster (mostly for kubelet)
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-writer
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]

---

# Full read access to the api and resources
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-reader
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
# Give admin, kubelet, kube-system, kube-proxy god access
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-write
subjects:
  - kind: User
    name: admin
  - kind: User
    name: kubelet
  - kind: ServiceAccount
    name: default
    namespace: kube-system
  - kind: User
    name: kube-proxy
roleRef:
  kind: ClusterRole
  name: cluster-writer
  apiGroup: rbac.authorization.k8s.io
```
 * https://github.com/kubernetes/minikube/issues/1734#issuecomment-323443032
 * https://github.com/rook/rook/pull/1107

/kind bug
